### ISSUE TITLE
Update node version

### ISSUE THREAD

**Issue by jbum** [aws-actions/configure-aws-credentials#1032]
### Describe the bug

When using configure-aws-credentials in a workflow, github reports that the version of node is deprecated, like so:

![CleanShot 2024-03-12 at 14 56 28](https://github.com/aws-actions/configure-aws-credentials/assets/287977/cd5fdf26-ceec-4a1f-804b-3c41448431c4)

### Expected Behavior

I would like the latest version of configure-aws-credentials to use a non-deprecated version of Node.

### Current Behavior

![CleanShot 2024-03-12 at 14 56 28](https://github.com/aws-actions/configure-aws-credentials/assets/287977/8c518820-31ca-484e-8198-b930a57df6bf)

### Reproduction Steps

Use configure-aws-credentials in a workflow.

Review the workflow action after it completes.

### Possible Solution

Insure all dependencies are up to date.

**Comment by tim-finnigan** [comment]
Hi @jbum thanks for reaching out. In `v4` the runtime was [upgraded](https://github.com/aws-actions/configure-aws-credentials/blob/main/CHANGELOG.md#400-2023-09-11) to `node20`. Can you try using `v4` (for example `uses: aws-actions/configure-aws-credentials@v4`) and let us know if you run into any issues?

**Comment by kellertk** [comment]
@jbum From your error message, you're using `@master` as the version tag for your action run. That has not been the name of the default branch of this repo for a long time, which is why you're pulling down a legacy version of this action that's running on an old version of node. Please update your workflow file.
