### ISSUE TITLE
error when using role-to-assume

### ISSUE THREAD

**Issue by ebenezen** [aws-actions/configure-aws-credentials#105]
As of 8/3/2020, we are seeing below error when using 

##[error]Missing required environment value. Are you running in GitHub Actions?

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.G_AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ env.G_AWS_ACCOUNT_ID }}:${{ env.G_ROLE_ASSUME }}
        role-duration-seconds: 1200

to debug further, when we printed all the env variables ( GITHUB_REPOSITORY, GITHUB_WORKFLOW, GITHUB_ACTION, GITHUB_ACTOR, GITHUB_REF, GITHUB_SHA ) ,  we noticed GITHUB_ACTION to be empty.

Appreciate any help to get this fixed.

**Comment by shun-tak** [comment]
this also happens in my env

**Comment by sauln** [comment]
Looks to be related to an issue with github actions themselves: actions/runner/issues/635

A possible fix is to use `GITHUB_ACTIONS` instead of `GITHUB_ACTION` as seen in codecov/codecov-bash/pull/341

**Comment by sergirosell** [comment]
also commented on the other issue already opened about env vars:
https://github.com/aws-actions/configure-aws-credentials/issues/80

**Comment by davidjdixon** [comment]
https://github.community/t/github-action-environment-variable-missing-breaking-issue/125913

> There was a bug in a recent runner rollout: https://github.com/actions/runner/releases/tag/v2.272.0. We progressively roll runner updates to customers so some customers were impacted by this update (it broke GITHUB_ACTION context, as you saw). We are rolling it back now and all customers should be fixed by 10 am EST.
> We apologize for the inconvenience and the issue here and have added some validation to the runner to make sure we have future coverage if the context is impacted before it rolls out to customers.

**Comment by pkandasamy91** [comment]
@ebenezen it looks like the release that causes this issue has been rolled back by Github. Wanted to confirm that this is no longer a problem for you before I close this issue.

**Comment by sauln** [comment]
Everything works for me now 👍

**Comment by sergirosell** [comment]
yes, after GitHub rolled out the change it start working again for us also, thanks ;)

**Comment by ebenezen** [comment]
Hi, yes, everything works now after GitHub made changes at their end. Thanks everyone for your support.
