### ISSUE TITLE
AWS SSO Support with aws-actions/configure-aws-credentials

### ISSUE THREAD

**Issue by kotowick** [aws-actions/configure-aws-credentials#1051]
### Feature description

I am trying to use `act` locally but `configure-aws-credentials` fails. Is there anyway to get this to work with AWS SSO from a local machine?

I tried with role-chaining too. 

The below config works in Github Actions, just not locally.

permissions:
  id-token: write
  contents: read 

- name: (Local) - Configure AWS Credentials
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: some_role
          role-session-name:  some_session
          aws-region: some_region

### Use Case

Using ACT locally

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by tim-finnigan** [comment]
Thanks for the feature request, it sounds like this is something worth looking more into. Can you provide any additional context regarding your use case? Specially, what you're currently doing with ACT and how you are currently blocked.

**Comment by stevenruizhang** [comment]
i execute aws sso login, and i can get dev profile result for aws configure list --profile my-dev-admin-profile in my local, but when running the pipeline i get error "Error loading SSO Token: Token for my-sso does not exist", is that any configuration missing?
![image](https://github.com/aws-actions/configure-aws-credentials/assets/13114985/24da4e98-ef3d-40d8-baff-d0b2a876968d)

![image](https://github.com/aws-actions/configure-aws-credentials/assets/13114985/b7ac93cc-bc92-4c60-96a7-2c2203e5a195)

name: 'Win_Deploy'

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: 'Terraform'
    runs-on: self-hosted
    steps:
    # Clone the repository to the GitHub Actions runner
    - name: Clone
      uses: actions/checkout@v2      
    # Configure AWS Credentials
    # You will need to replace <IAM_ROLE> with the IAM role ARN you created in the previous step
    - name: Get AWS Configure List
      run: |
          aws configure list --profile my-dev-admin-profile
    - name: Publish on aws dev env
      if: github.ref == 'refs/heads/master'
      run: ./publish_win.ps1 dev


#1068

**Comment by stevenruizhang** [comment]
@tim-finnigan  @swinton  @jplock any updates on that?
