### ISSUE TITLE
Credentials could not be loaded in self x64 windows hosted for aws-actions/configure-aws-credentials 

### ISSUE THREAD

**Issue by stevenruizhang** [aws-actions/configure-aws-credentials#1068]
### Describe the bug

hi team,
  I install  self-hosted runner according to git hub guideline in my local windows11 , and i use aws sso login , get the aws credential in my local.
aws cli:
![image](https://github.com/aws-actions/configure-aws-credentials/assets/13114985/6d146d97-8dfa-4f16-907f-1af270931976)

according to this doc , **if the local runner has access to AWS credentials, such as an EC2 instance, then you do not need to provide IAM user access key credentials to this action. We will use the standard AWS JavaScript SDK credential resolution methods to find your credentials,** 
https://github.com/aws-actions/configure-aws-credentials

but seems like the results shows "**Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers**"

any configurations missing?

in the my terraform repo code, i use different profile setting in my local for different aws environment/account under different terraform folder(different terraform state file). So i need at least one profile can work in pipeline line, if also can configure the profile in git actions is perfect 

give one aws dev account for example, i can use the profile approach setup resource in my local
![image](https://github.com/aws-actions/configure-aws-credentials/assets/13114985/ef28c7f8-8f5c-4a80-84e3-de8fc59d083e)

### Expected Behavior

i suppose the result running the aws sts get-caller-identity in pipeline get the same result from my local aws sts command line , but get error in pipeline

### Current Behavior

Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers
![image](https://github.com/aws-actions/configure-aws-credentials/assets/13114985/e32ce550-06c1-453b-8d74-024e34491a19)

### Reproduction Steps

1) install the self x64 windows hosted in your local windows11
2) config the aws sso login in your  local windows11
3) set below workflow file in the repo
4) trigger the pipeline manually

**Workflow file for this run:**
name: 'Win_Deploy'

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: 'Terraform'
    runs-on: self-hosted
    steps:
    # Clone the repository to the GitHub Actions runner
    - name: Clone
      uses: actions/checkout@v2      
    # Configure AWS Credentials
    # You will need to replace <IAM_ROLE> with the IAM role ARN you created in the previous step
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:        
        aws-region: eu-central-1   
    - name: Sts GetCallerIdentity
      run: |
          aws sts get-caller-identity
    - name: List S3 bucket      
      run: |
          aws s3 ls    
    - name: Publish on aws dev env
      if: github.ref == 'refs/heads/master'
      run: ./publish_win.ps1 dev

**Comment by stevenruizhang** [comment]
if i remove all aws credential in pipeline, i will get Error: failed to get shared config profile, my-dev-admin-profile when execute terraform plan command line 
**Workflow file for this run:**
name: 'Win_Deploy'

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: 'Terraform'
    runs-on: self-hosted
    steps:
    # Clone the repository to the GitHub Actions runner
    - name: Clone
      uses: actions/checkout@v2      
    # Configure AWS Credentials
    # You will need to replace <IAM_ROLE> with the IAM role ARN you created in the previous step
    - name: Get AWS Configure List
      run: |
          aws configure list 
    - name: Publish on aws dev env
      if: github.ref == 'refs/heads/master'
      run: ./publish_win.ps1 dev
    
 **pipeline error**
![image](https://github.com/aws-actions/configure-aws-credentials/assets/13114985/5771d1d3-4e98-4216-9d8c-1cf5b3194734)

**Comment by tim-finnigan** [comment]
Thanks for reaching out, I think maybe we need to reopen https://github.com/aws-actions/configure-aws-credentials/issues/1051 to track the feature request for supporting SSO. Do you agree or have any updates on your end?
