### ISSUE TITLE
Not recognizing inputs for configuring credentials

### ISSUE THREAD

**Issue by mikeheft** [aws-actions/configure-aws-credentials#1158]
### Describe the bug

I am receiving an error in my action logs about an error:
```bash
> Run aws-actions/configure-aws-credentials@v4
  with:
    audience: sts.amazonaws.com
  Error: Input required and not supplied: aws-region
```

However, here is my job step. I had it set with `${{ secrets.AWS_REGION }}` but that was failing as well, so I hard coded it. 

```yaml
permissions:
  id-token: write
  contents: read
steps:
  - name: Set up AWS credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-region: us-west-2
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

Here are the logs from that step. The secrets in question are all set properly. This was working previously then I moved it to a reusable workflow and that is when it started to fail.

```
##[debug]Evaluating condition for step: 'Set up AWS credentials'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Set up AWS credentials
##[debug]Register post job cleanup for action: aws-actions/configure-aws-credentials@v4
##[debug]Loading inputs
##[debug]Evaluating: secrets.AWS_ACCESS_KEY_ID
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'AWS_ACCESS_KEY_ID'
##[debug]=> null
##[debug]Result: null
##[debug]Evaluating: secrets.AWS_SECRET_ACCESS_KEY
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'AWS_SECRET_ACCESS_KEY'
##[debug]=> null
##[debug]Result: null
##[debug]Evaluating: secrets.AWS_REGION
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'AWS_REGION'
##[debug]=> null
##[debug]Result: null
##[debug]Loading env
Run aws-actions/configure-aws-credentials@v4
Error: Input required and not supplied: aws-region
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Set up AWS credentials
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Expected it to configure the credentials successfully as it did previously

### Current Behavior

```bash
> Run aws-actions/configure-aws-credentials@v4
  with:
    audience: sts.amazonaws.com
  Error: Input required and not supplied: aws-region
```

### Reproduction Steps

- Add secrets to repo
- Create an action
- Ensure Action has read/write permissions
- Run action
- Fails

### Additional Information/Context

The secrets in question are all set properly. This was working previously then I moved it to a reusable workflow and that is when it started to fail.

**Comment by kellertk** [comment]
Your run output indicates that your secrets aren't being picked up at all by the action run. Are you sure you have permissions to read them? Organization-level secrets might have different permissions and secrets aren't populated to forked repositories. Please review https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions
