### ISSUE TITLE
feat: Add cli install option

### ISSUE THREAD

**Issue by davidkarlsen** [aws-actions/configure-aws-credentials#120]
It would be handy if the action could also have a flag `install_cli: true|false, default false` in order to install the latest cli on self-hosted runners.
Related https://github.com/aws-actions/configure-aws-credentials/issues/113

**Comment by peterwoodworth** [comment]
Thanks for the request @davidkarlsen, could you please explain why we would want to do this when runners come with this preinstalled? If the latest version is required, that could be configured through a separate step like seen [here](https://stackoverflow.com/a/70689416). If enough people think it would be useful for us to directly support this then we can think about implementing it 🙂
