### ISSUE TITLE
Error: Need to perform AWS calls for account  ***, but no credentials have been configured

### ISSUE THREAD

**Issue by wwhchung** [aws-actions/configure-aws-credentials#1201]
### Describe the bug

Within the last two hours, we are unable to use aws cdk deploy within a github action, with the error:
“ Need to perform AWS calls for account ***, but no credentials have been configured”

we have tried the runner action:
aws-actions/configure-aws-credentials@v2 v3 and v4

we have double checked that the following values are correct:
aws-access-key-id
‎aws-secret-access-key
aws-region

are you aware of any issues that may hav occurred within the last two hours (looking like Nov 14, 2024 00:00 GMT)

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

CDK deploy works within a github action 

### Current Behavior

Receiving an error:
Need to perform AWS calls for account  ***, but no credentials have been configured

### Reproduction Steps

Configure to use credentials as per above.

**Comment by wwhchung** [comment]
Update: I can confirm that the credentials are correct, because I can see via the IAM panel that the last service used was 'sts'.  However, when I do cdk deploy --verbose, it gives the following error:
[03:21:38] Looking up default account ID from STS
[03:21:38] Unable to determine the default AWS account (InvalidClientTokenId): The security token included in the request is invalid

So, the credentials appear correct, as IAM shows it being used and accessing STS, but for some reason the default account id can't be determined.

**Comment by logg926** [comment]
+1

**Comment by wwhchung** [comment]
We resolved this, aws-cdk@2.167.0 is broken.

Use aws-cdk@2.166.0
