### ISSUE TITLE
Add Support for ECDSA-based Signatures of OIDC Tokens

### ISSUE THREAD

**Issue by garysassano** [aws-actions/configure-aws-credentials#1211]
### Describe the feature

I would like to request support for ECDSA-based signatures of OpenID Connect (OIDC) tokens in the `configure-aws-credentials` GitHub Action. AWS STS recently announced support for ECDSA signatures, allowing users to choose between RSA and ECDSA keys for signing OIDC JWTs.

For more details, please refer to the [AWS announcement](https://aws.amazon.com/about-aws/whats-new/2024/11/aws-sts-ecdsa-based-signatures-oidc-tokens/).

### Use Case

This enhancement would improve security and flexibility for users who want to leverage ECDSA's strong security with smaller key sizes compared to RSA. It would also allow users to adopt this feature without any changes to their existing AWS IAM configurations.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by kellertk** [comment]
Does GitHub support ECDSA-signed JWTs? https://token.actions.githubusercontent.com/.well-known/openid-configuration shows that the supported algorithm is `RS256` only. As far as I can tell neither the `@actions/core` toolkit nor GitHub support ECDSA keys yet. Presently this action only supports getting a token from GitHub's OIDC provider.
