### ISSUE TITLE
set-env and add-path commands are Deprecated

### ISSUE THREAD

**Issue by mforutan** [aws-actions/configure-aws-credentials#140]
Running version 1.5.0 and started seeing this warning:

```
The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
More details:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by itchyny** [comment]
In the version [`1.5.3`](https://github.com/aws-actions/configure-aws-credentials/releases/tag/v1.5.3), the `@actions/core` package is [already updated to `1.2.6`](https://github.com/aws-actions/configure-aws-credentials/blob/v1.5.3/package-lock.json#L7-L11).

**Comment by mforutan** [comment]
Thank you @itchyny, upgrading to the 1.5.3 removed the warnings.
