### ISSUE TITLE
Permission denied when running aws-actions/configure-aws-credentials@v1.5.4

### ISSUE THREAD

**Issue by ahtsan** [aws-actions/configure-aws-credentials#156]
The error message is
`Error: EACCES: permission denied, open '/__w/_temp/_runner_file_commands/set_env_ce6e4009-aa1a-48b8-ab8b-8c217be6610f'`

**Comment by ahtsan** [comment]
After I ran `sudo chown -R <my-user>:<my-usergroup> /__w/, I got `Error: Access to the path `/home/runner/work/_temp/_github_workflow/event.json' is denied.`
I'm using a custom docker image

**Comment by allisaurus** [comment]
@ahtsan where are you trying to run the action? Are you seeing this on a self-hosted runner?

**Comment by ahtsan** [comment]
I was using a custom user to run the action. Using root resolves the issue.
