### ISSUE TITLE
`role-skip-session-tagging: false` skips session tagging

### ISSUE THREAD

**Issue by gabegorelick** [aws-actions/configure-aws-credentials#199]
[`getInput` always returns a string](https://github.com/actions/toolkit/blob/e76decaf8a52bc981d17ddd3efcca548f6bc1a0e/packages/core/src/core.ts#L77-L92), and this action doesn't convert the return value to a boolean. So if you specify `role-skip-session-tagging: false`, you won't get session tagging.

https://github.com/aws-actions/configure-aws-credentials/blob/3042b009625a34bedaba3cc28b2713a8e11d4f2b/index.js#L206

https://github.com/aws-actions/configure-aws-credentials/blob/3042b009625a34bedaba3cc28b2713a8e11d4f2b/index.js#L58

The obvious workaround is to just remove the `role-skip-session-tagging` option instead of specifying `role-skip-session-tagging: false`, but it's definitely confusing that `role-skip-session-tagging: false` doesn't work as expected.

**Comment by allisaurus** [comment]
This should be fixed in [1.5.10](https://github.com/aws-actions/configure-aws-credentials/blob/v1.5.10/CHANGELOG.md#1510-2021-06-01)!
