### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by FabianSandmann** [aws-actions/configure-aws-credentials#222]
Hello there,

it would be really nice to set a HTTP or HTTPS proxy server in the step configuration, or to just pass through the already set environmental settings of the runner. 

If it is already possible and I just missed it where to set it, let me know.

**Comment by paragbhingre** [comment]
Hi @FabianSandmann, Thank you for reporting this!

Just to make sure that we understand your request I am attaching one link [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-proxy.html) and want you to confirm is that what you want?
Also take look at [this](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/http_proxy_config.html) for more reference.
In advanced apologies if you have already taken a look at these resources.

**Comment by FabianSandmann** [comment]
Hey @paragbhingre. 
Yeah this is exactly what I need. 
It would help me a lot, if the action could access AWS through our proxy server.

**Comment by jpm63** [comment]
@paragbhingre - we're also in need of this functionality. Can you provide any input as to when #246 might be reviewed?

**Comment by peterwoodworth** [comment]
Hey all, just to let you know if you're following this issue that #246 is in the process of being reviewed and it will hopefully be merged soon. Thanks for your patience!

**Comment by austinvalle** [comment]
@peterwoodworth Thanks for merging that PR, #246. Are there plans to update the release [v1](https://github.com/aws-actions/configure-aws-credentials/releases/tag/v1)
 tag, or should we point directly to the commit a54abfbe4520717bf626ce457d3a94b5d72a24e9
