### ISSUE TITLE
web-identity-token-file is not in v1, but readme says it is

### ISSUE THREAD

**Issue by mhenderson-t2** [aws-actions/configure-aws-credentials#266]
The readme indicates that `web-identity-token-file` is present in `@v1`

> You can configure your workflow as follows in order to use this file:
> 
> ```
> uses: aws-actions/configure-aws-credentials@v1
> with:
>   aws-region: us-east-2
>   role-to-assume: my-github-actions-role
>   web-identity-token-file: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
> ```

However it appears this functionality was [added 4th August](https://github.com/aws-actions/configure-aws-credentials/pull/240) and the module has not been released since then. Hence you cannot use this feature as it is documented. 

I have worked around this by

```
uses: aws-actions/configure-aws-credentials@master
```

But I cannot recommend this to others, as it does not pin the module to a stable (or released) version. However this may be worth either documenting, or removing the documentation until it has been released.

**Comment by paragbhingre** [comment]
We have now released configure-aws-credentials. V1 will now have the web-identity-token-file related changes.

**Comment by peterwoodworth** [comment]
This has been released 🙂
