### ISSUE TITLE
getting OIDC credentials not working

### ISSUE THREAD

**Issue by androidwiltron** [aws-actions/configure-aws-credentials#273]
the new functionality to use OIDC to get the credentials was working on the `master` branch untill very recently. 

error:

```
Error: core.getIDToken is not a function
```

**Comment by richardhboyd** [comment]
Looking into this

**Comment by richardhboyd** [comment]
ohhhh, i wonder if we need to bump the GHA core version in package.json

**Comment by richardhboyd** [comment]
we're going to revert the most recent change that introduced the actions/core API for getting the token. Once the API stabilizes we will re-introduce the getIDToken() changes.

**Comment by androidwiltron** [comment]
Implemented now. Working and tested
