### ISSUE TITLE
No OpenIDConnect provider found in your account

### ISSUE THREAD

**Issue by mitch-keenan** [aws-actions/configure-aws-credentials#280]
Had an problem crop up this morning trying to run an action using OIDC auth as described [here](https://github.com/aws-actions/configure-aws-credentials/issues/271#issuecomment-931805471) and wanted to raise an issue in case anyone runs into the same thing:

Action fails with following error:
```
Error: No OpenIDConnect provider found in your account for https://token.actions.githubusercontent.com
```

I was able to change my IAM OIDC/role definition to change `vstoken.` to `token.` and then it authenticated successfully, but I can't seem to find a mention of this change anywhere from Github themselves.

See [PR281](https://github.com/aws-actions/configure-aws-credentials/pull/281) for my changes to update the example iam role template

**Comment by Nirrleybo** [comment]
I'm experiencing the same issue. Had to change the url to **token** but unlike you, my authentication step is failing...

**Comment by richardhboyd** [comment]
I'm looking into this now. GH is still actively developing this feature so there are breaking changes that are happening until they officially GA the capability.

**Comment by richardhboyd** [comment]
@Nirrleybo I think the audience is `sigstore` for now. GH released teh ability to set an arbitrary audience yesterday and I am working on adding that to the action now. When it's done, we will set the audience to `sts.amazonaws.com` when redeeming the JWT for AWS credentials.

**Comment by alblue** [comment]
Would it be worth doing it the other way around, and rebasing your change on top of this one? Then instead of changing the default (which will break existing clients) you could simply default it to 'sigstore' and then encourage (in documentation, getting started guides etc.) to explicitly put "audience: sts.amazonaws.com" instead?

**Comment by richardhboyd** [comment]
We don't want the default to be sigstore because it poses a risk of causing a confused deputy problem. This change hasn't been officially released yet (in the v1 tag) so the only people who have taken a dependency on it are people who have explicitly set their action to either `master` or pinned to a specific commit.

**Comment by saito-sv** [comment]
> @Nirrleybo I think the audience is `sigstore` for now. GH released teh ability to set an arbitrary audience yesterday and I am working on adding that to the action now. When it's done, we will set the audience to `sts.amazonaws.com` when redeeming the JWT for AWS credentials.

changing audience to `sigstore` seemed to have done the trick.

**Comment by DanK-FD** [comment]
If you are suddenly receiving an `Incorrect token audience` error, this [change](https://github.com/aws-actions/configure-aws-credentials/commit/036a4a1ddf2c0e7a782dca6e083c6c53e5d90321#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L306-R290) has required the audience be changed from `sigstore` to `sts.amazonaws.com` (as previously [commented](https://github.com/aws-actions/configure-aws-credentials/issues/280#issuecomment-939280568)).

**Comment by peterwoodworth** [comment]
This issue seems it was from before the feature became available. Closing out, ping if you feel this was in error.

**Comment by newfunda** [comment]
@richardhboyd , For me I tried all ways and trust json etc looks all good but still getting the same error, any other clue for me? Tried with v2 also but same error.

aws-actions/configure-aws-credentials@v1
Error: No OpenIDConnect provider found in your account for https://token.actions.githubusercontent.com/

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::xxxxxxxx:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com",
                    "token.actions.githubusercontent.com:sub": "repo:user/repo-name:*"
                }
            }
        }
    ]
}

**Comment by peterwoodworth** [comment]
@newfunda Have you created an identity provider in your AWS account? See [here](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#adding-the-identity-provider-to-aws)
