### ISSUE TITLE
Improve error messaging

### ISSUE THREAD

**Issue by richardhboyd** [aws-actions/configure-aws-credentials#282]
Currently any number of failures result in `Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers` which isn't terribly helpful. We should better surface error messages for:

- the workflow not having the correct permissions
- IAM refusing to grant credentials for a token
- others?

**Comment by jazanne** [comment]
I see the error fairly frequently in one of my repos - it's intermittent and rerunning a workflow will generally work / not produce this error. However, having this pop up as often as it does slows down my CI/CD process. I'd love more info on what's causing it and why it only happens sometimes, but not consistenly.

**Comment by jtheuer** [comment]
same here, got `Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers` and would really like to know where to start looking.

Any chance the error messages / logs are improved?

**Comment by peterwoodworth** [comment]
We should absolutely improve error messaging. I'll try to update this thread with the errors I and others come across that are unclear

**Comment by astropanic** [comment]
Any updates here?

I have a job on a self hosted runner, on one container it runs smoothly, on another I'm getting: `Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers`

If the error message would be more specific, I could tell where the problem resides.

**Comment by peterwoodworth** [comment]
The error messaging will be improved upon in v3, however I can't yet give a date for when that will be available.

@astropanic feel free to submit a new issue or discussion with further details including your workflow files

**Comment by blimmer** [comment]
For me, it was because I missed adding the `id-token` permission, which is in the README, I just missed it: https://github.com/aws-actions/configure-aws-credentials/blob/746d33e7c1cc7b6e40a836b0f2ef033136aa6b2a/README.md#L73-L76

Leaving this note here for future travelers.

**Comment by jwalton** [comment]
For me, every time it's because I forget to add the permissions token.  :P  It would ber nice if the error message told you to check this.

**Comment by peterwoodworth** [comment]
Error messaging and our docs should be improved overall for this action in `v3`. Please open any issues if you encounter any error messages that are unclear.
