### ISSUE TITLE
Document `mask-aws-account-id` input

### ISSUE THREAD

**Issue by ckingbailey** [aws-actions/configure-aws-credentials#304]
The input `mask-aws-account-id`, which prevents the action from doing addMask on the value of AWS account id, is not documented.

I spent some hours banging my head against why the AWS account id output from a job was being redacted in dependent jobs that were trying to use it to compose resource ARNs. [This helpful soul](https://github.community/t/skip-output-aws-account-id-since-it-may-contain-secret/123791/9) on the GitHub Community Support forum pointed me to this undocumented input as the culprit. It would be nice if it was documented in the action's README so that others don't have to go digging in SO to figure out why their job output is being redacted.

One note about documenting this: the description of the input in action.yml says the allowed values are `true` and `false`, but, per the recommendation of that GH Community post, I gave it the value `'no'` and it worked. What are the allowed values for this input?

**Comment by kellertk** [comment]
Regarding allowed values, https://github.com/aws-actions/configure-aws-credentials/blob/master/index.js#L180 shows the answer: anything that isn't `true` is considered `false`.

This is presently documented in the [action definition file](https://github.com/aws-actions/configure-aws-credentials/blob/master/action.yml#L25)

**Comment by peterwoodworth** [comment]
We should absolutely document this, if no one creates a PR for this i'll try to get to it soon

**Comment by 1oglop1** [comment]
@peterwoodworth 
What's the reason behind masking Account ID by default when it is not considered sensitive information?

https://www.lastweekinaws.com/blog/are-aws-account-ids-sensitive-information/#:~:text=AWS%20account%20IDs%20are%20not%20considered%20sensitive%20and%20you%20need,medium%20that%20you'd%20like.

**Comment by peterwoodworth** [comment]
I can't really comment on why this was done, because the current owners of this action aren't the ones who originally wrote it. We're going to adjust the default in the next major version https://github.com/aws-actions/configure-aws-credentials/issues/459
