### ISSUE TITLE
Error: Not authorized to perform sts:AssumeRoleWithWebIdentity

### ISSUE THREAD

**Issue by shinebayar-g** [aws-actions/configure-aws-credentials#318]
I followed [this documentation](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services) to setup my OIDC provider.

OIDC trust relationship doc:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::123456789:oidc-provider/token.actions.githubusercontent.com"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "token.actions.githubusercontent.com:aud": "https://github.com/my-org"
        }
      }
    }
  ]
}
```

Added permissions to workflow:

```yml
permissions:
  id-token: write
  contents: read  # It wasn't mentioned on the docs, without this checkout action doesn't work!
```

Unfortunately Github Actions doesn't work. I'm getting:

```
Error: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

What's the fix?

**Comment by shinebayar-g** [comment]
As others [suggested](https://github.com/aws-actions/configure-aws-credentials/issues/271) changing 

```json
"StringEquals": {
          "token.actions.githubusercontent.com:aud": "https://github.com/my-org",
}
```

to

```json
"StringEquals": {
          "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
}
```

works.

**Comment by shinebayar-g** [comment]
> 

Ah I see. I definitely overlooked that part! Thank you very much.

**Comment by mathix420** [comment]
Thanks, that helped me finding my issue.
In my case the issue was also on the condition, I went from this
```json
"Condition": {
    "ForAllValues:StringEquals": {
        "token.actions.githubusercontent.com:sub": "repo:myusername/myrepo:*",
        "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
    }
}
```

To this

```json
"Condition": {
    "ForAllValues:StringLike": {
        "token.actions.githubusercontent.com:sub": "repo:myusername/myrepo:*",
        "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
    }
}
```
Hope this can help someone else!

**Comment by Andrew-Chen-Wang** [comment]
that worked @mathix420 thanks! (made a PR in [github docs](https://github.com/github/docs/pull/18550))

**Comment by lucasgherculano** [comment]
If I want to allow all repos in the org how would that be?

`        "token.actions.githubusercontent.com:sub": "repo:org-name*",
`
tried this but it didnt work

**Comment by Andrew-Chen-Wang** [comment]
@lucasgherculano try org/* (ie missing the /)

**Comment by dankore** [comment]
> If I want to allow all repos in the org how would that be?
> 
> ` "token.actions.githubusercontent.com:sub": "repo:org-name*",` tried this but it didnt work

**Try:**

```
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::XXXXXXXX/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "ForAllValues:StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:MY-ORG-NAME/*"
                }
            }
        }
    ]
}
```

**Comment by lucasgherculano** [comment]
Yes, i've done it, it worked, thanks

**Comment by jigar-bhalodia** [comment]
> Thanks, that helped me finding my issue. In my case the issue was also on the condition, I went from this
> 
> ```json
> "Condition": {
>     "ForAllValues:StringEquals": {
>         "token.actions.githubusercontent.com:sub": "repo:myusername/myrepo:*",
>         "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
>     }
> }
> ```
> 
> To this
> 
> ```json
> "Condition": {
>     "ForAllValues:StringLike": {
>         "token.actions.githubusercontent.com:sub": "repo:myusername/myrepo:*",
>         "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
>     }
> }
> ```
> 
> Hope this can help someone else!

Hey @mathix420, heads up, using `ForAllValues` by itself is dangerous because it returns true if there are no keys in the request, or if the key values resolve to a null data set, such as an empty string.

Docs for reference: 
- https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#configuring-the-role-and-trust-policy
- Check ForAllValues section here -> https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_multi-value-conditions.html#reference_policies_multi-key-or-value-conditions

**Comment by jigar-bhalodia** [comment]
Considering you shouldn't use `ForAllValues` by itself in Allow list, following works well.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::123456123456:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:octo-org/octo-repo:*"
                },
                "ForAllValues:StringEquals": {
                    "token.actions.githubusercontent.com:iss": "https://token.actions.githubusercontent.com",
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
```

**Comment by mathix420** [comment]
Thanks for noting this @jigar-bhalodia, I update my last post so others follows the right path!

**Comment by qventus-azepeda** [comment]
After hitting my head around for a day, this solved it, just having one conditional after all:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::351480950201:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "ForAllValues:StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:My-Org/*"
                }
            }
        }
    ]
}
```

**Comment by cepefernando** [comment]
I was able to fix this by just removing one conditional, this helped a lot. Thank you.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::xxxxxx:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "ForAllValues:StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:My-ORG/*"
                }
            }
        }
    ]
}
```

**Comment by BradyRyun** [comment]
For anyone running into this, it _**is**_ case sensitive for the org name. For instance, my condition looks like:

`"token.actions.githubusercontent.com:sub": "repo:BradyRyun/*",`

**Comment by pawelkolak** [comment]
Hi, have the same issu
`Error: Could not assume role with OIDC: Not authorized to perform sts:AssumeRoleWithWebIdentity`

OIDC trust relationship doc:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::XXXXXX:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "token.actions.githubusercontent.com:sub": "repo:company/repo*",
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
```

Yaml connection:
```
- name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::XXXXX:role/AmplifyGithubActionService
          role-session-name: DeployAmplify
```
          
I'm still getting the same error. Adding a new identity provider didn't help at all. Does anyone have any ideas on how to resolve or debug this?

**Comment by PatrickPrakash** [comment]
> For anyone running into this, it _**is**_ case sensitive for the org name. For instance, my condition looks like:
> 
> `"token.actions.githubusercontent.com:sub": "repo:BradyRyun/*",`

Thank you for this!!

**Comment by liviudobrea** [comment]
> "StringEquals": {
>                     "token.actions.githubusercontent.com:sub": "repo:company/repo*",

This needs to be inside a StrinLike claim, not StringEquals
