### ISSUE TITLE
Set Repo Secrets from values retrieved from AWS Secrets Manager

### ISSUE THREAD

**Issue by devoredevelops** [aws-actions/configure-aws-credentials#336]
Curious to know if it is possible to *set* repo Secrets from values retrieved from aws secrets manager. Right now I know it's possible to set GitHub Secrets via the `gh cli` but I was wanting to do it via a custom action.

My currently solution uses the `aws cli` to retrieve secret values (decrypted `SecureString`) but I'm having to store these values as a step's environment variables and it exposes these values to the developer and to our admins. IIRC there's a way to mask step outputs and values but I was looking for a more automated/fail-proof solution.

**Comment by kellertk** [comment]
This is possible using the [GitHub API](https://docs.github.com/en/rest/reference/actions#create-or-update-a-repository-secret), but this action's purpose is just to export environment variables. If you want to interact with repository secrets, you'll need to use a different action :)
