### ISSUE TITLE
Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers

### ISSUE THREAD

**Issue by stardustman** [aws-actions/configure-aws-credentials#337]
I notice the github actions support OpenID Connect (OIDC), but is there a way I don't use it?
the actions report this error?
how to fix it ? I try use the @master, it still not work.
help!!!

**Comment by a-h** [comment]
Have you seen this? https://github.com/aws-actions/configure-aws-credentials/issues/271#issuecomment-931012696
