### ISSUE TITLE
Region is getting masked

### ISSUE THREAD

**Issue by vesubramanian** [aws-actions/configure-aws-credentials#368]
On using this action, the region is also getting masked.

**Comment by yaldram** [comment]
Got my solution if we don't want your aws region to get masked please don't use it as a secret like {{secrets.AWS_REGION}} simply hard code it in our workflow commands.

**Comment by yaldram** [comment]
- name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

**Comment by vesubramanian** [comment]
I am not using it as a secret. But instead of hard coding it, I use a variable. But still it is masked.

**Comment by peterwoodworth** [comment]
This action doesn't set the region as a secret in code like it does with the keys. Can you please share reproduction steps i.e. your workflow file @vesubramanian?

**Comment by vesubramanian** [comment]
PFB. I am not at all using region as a secret, but reading from the matrix. But still it is masked in the output. You can try this. When I reached out to the support, they were also able to reproduce this and they said, they have communicated this to the engineering team, who were also able to reproduce this. But they haven't given an ETA for the fix.

`  - name: Configure AWS Credentials for Target Account
          uses: aws-actions/configure-aws-credentials@v1
          with:
             aws-access-key-id: ${{ secrets[env.ACCESS_KEY_ID_VAR] }}
             aws-secret-access-key: ${{ secrets[env.ACCESS_KEY_VAR] }}
             aws-region: ${{ matrix.region }}
             mask-aws-account-id: 'false'`

**Comment by peterwoodworth** [comment]
Please feel free to ping me if this issue persists and you have more info on how I can reproduce it. Thanks
