### ISSUE TITLE
[ Feat request ] Multi-account setup

### ISSUE THREAD

**Issue by cig0** [aws-actions/configure-aws-credentials#376]
Hi,

Do you plan to add a multi-account setup for this action?

We have some infrastructure pipelines that work across different accounts; at the moment we are using a `case` statement to manage which set of secrets should be used depending on which environment we are deploying our infrastructure. It would be great though, to be able to do the same with this action.

Thanks

**Comment by ghostsquad** [comment]
related #432

**Comment by peterwoodworth** [comment]
We have a couple related issues to this like #112, we will see what we can do about use cases like this. Thanks!
