### ISSUE TITLE
Support setting credentials as action outputs instead of setting environment variables

### ISSUE THREAD

**Issue by paulolieuthier** [aws-actions/configure-aws-credentials#379]
This is useful for using the action in a composite action in a self-contained way, without altering the runner environment for the job.

**Comment by jim-hill-r** [comment]
This should solve this: https://github.com/aws-actions/configure-aws-credentials/pull/325

**Comment by peterwoodworth** [comment]
This is now supported in `v3` with `output-credentials` https://github.com/aws-actions/configure-aws-credentials#retrieving-credentials-from-step-output-assumerole-with-temporary-credentials
