### ISSUE TITLE
Inaccessible host: `sts.eu-central-1.amazonaws.com' at port `undefined'.

### ISSUE THREAD

**Issue by lcmgh** [aws-actions/configure-aws-credentials#415]
Environment: corporate, self hosted runner

My self hosted runners have a proxy setup as described here: https://docs.github.com/en/actions/hosting-your-own-runners/using-a-proxy-server-with-self-hosted-runners

A prior action `Slidem/inplace-envsubst-action` I'm running works fine and can fetch internet dependencies, therefore I assume internet connectivity is OK but `aws-actions/configure-aws-credentials@v1` fails with:

```
Run aws-actions/configure-aws-credentials@v1
  with:
    aws-access-key-id: ***
    aws-secret-access-key: ***
    aws-region: eu-central-1
    role-to-assume: arn:aws:iam::xxxx:role/xxxxxxxxxxxxxxx
    role-duration-seconds: 1[20](https://xxx/runs/146919?check_suite_focus=true#step:5:20)0
    role-skip-session-tagging: true
  env:
    KUBERNETES_CLUSTER: xxxx
Error: Inaccessible host: `sts.eu-central-1.amazonaws.com' at port `undefined'. This service may not be available in the `eu-central-1' region.
```
Any ideas?

**Comment by lcmgh** [comment]
After ensuring that `http_proxy` and `https_proxy` env. variables are set on the runner curl call to the endpoint works fine without additional flags but the action still fails with same error.

**Comment by lcmgh** [comment]
Solution seems to be https://github.com/aws-actions/configure-aws-credentials/pull/246. Can you please merge :)

**Comment by peterwoodworth** [comment]
Closing this out in favor of #222, we're hoping to merge #246 soon so stay tuned 🙂
