### ISSUE TITLE
Access to secrets in case of pull_request_review triggered from fork

### ISSUE THREAD

**Issue by suppamax** [aws-actions/configure-aws-credentials#416]
I would like to trigger an Action accessing AWS Codebuild via an approved PR review.
PRs are originated from a forked repository.
The target repository is public.
Now I get
```
Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers
```
I think the reason is that it is not possible to access secrets from a PR from fork.
Is there a way to workaround my problem?
I see there is a `pull_request_target` event which allows write access to token-id, but it's not clear to me how to make use of this feature here.

**Comment by ganeshnj** [comment]
By default I think not allowing credentials access for forked PR is good. But there has to be a way to manual trigger the action which override the behavior.

**Comment by peterwoodworth** [comment]
Yes, you will want to use `pull_request_target` in this case. Using this allows you to run the action in the base repository within the context of the PR base branch. This will allow you to use the secrets of your base repository on pull_request events. For more info see the Github docs [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)

If this doesn't help I might need more context into what exactly you're trying to accomplish and how

**Comment by zomars** [comment]
When requesting changes to a PR coming from a fork I'm trying to set the PR back to draft. Which is not possible with GITIHUB_TOKEN. But adding a PAT also doesn't work because secrets aren't available either on `pull_request_review` from forked PRs.

**Comment by zomars** [comment]
pull_request_target doesn't help with this
