### ISSUE TITLE
Action no longer allows environment variables to be passed as arguments

### ISSUE THREAD

**Issue by kevin-beatdapp** [aws-actions/configure-aws-credentials#43]
The Github runner cannot resolve the STS client hostname when the  `aws-region` is passed as an environment variable argument:

![image](https://user-images.githubusercontent.com/51331860/76120694-e2a69800-5fa6-11ea-872c-71f03207aaad.png)

I fixed this issue by passing in the argument manually, however https://github.com/aws-actions/configure-aws-credentials/commit/816f5cc0cf79541b2a6d639e8f93ae43aadaf09c introduced a change that broke previously working workflows.

**Comment by clareliguori** [comment]
Based on this community forum post, I believe the correct syntax for passing the environment variable as an input to the action should be `aws-region: ${{env.AWS_DEFAULT_REGION}}`.  Your current syntax passes the region as the literal string `$AWS_DEFAULT_REGION`.  I can add some validation around that string to provide a better error message.

https://github.community/t5/GitHub-Actions/How-to-pass-environment-variable-to-an-input/td-p/32003

**Comment by clareliguori** [comment]
The validation change is pushed to the v1 tag now, so you should get a clearer error message around the region string.
