### ISSUE TITLE
aws eks update-kubeconfig invalid apiVersion

### ISSUE THREAD

**Issue by Iliabuleh** [aws-actions/configure-aws-credentials#438]
Please update aws-sdk version accordingly
https://github.com/aws/aws-cli/issues/6920#issuecomment-1119926885

Currently using latest version of kubeconfig is broken:
https://github.com/aws/aws-cli/issues/6920

**Comment by mikejoseph-ef** [comment]
same here, getting error:

```bash
getting credentials: decoding stdout: no kind “ExecCredential” is registered for version “[client.authentication.k8s.io/v1alpha1](http://client.authentication.k8s.io/v1alpha1)” in scheme “pkg/client/auth/exec/exec.go:62”
```

**Comment by fhuaddeterminas** [comment]
Please we need help urgently here.

**Comment by je117er** [comment]
Upgraded to the latest version of aws but the same error persisted. Looks like I'll have to downgrade kubectl.

**Comment by fhuaddeterminas** [comment]
> Upgraded to the latest version of aws but the same error persisted. Looks like I'll have to downgrade kubectl.

Have you tried that? Did it work?

**Comment by fhuaddeterminas** [comment]
Guys, there is a workaround for the main time.

Scroll through this github issue https://github.com/aws/aws-cli/issues/6920

**Comment by bitbrain** [comment]
@fhuaddeterminas I also found a permanent fix that does not require downgrading: https://github.com/aws/aws-cli/issues/6920#issuecomment-1121127729

**Comment by peterwoodworth** [comment]
This issue seems resolved (plus I don't think this is an issue with this action in the first place) so I'm going to close it. Thanks all who helped find the fix for this
