### ISSUE TITLE
Handle security update

### ISSUE THREAD

**Issue by hencrice** [aws-actions/configure-aws-credentials#46]
https://github.com/aws-actions/configure-aws-credentials/network/alert/package-lock.json/minimist/open

Traced the dependency graph and it appears like jest->@jest/core->jest-config->babel/core->json5 2.1.1 ->minimist ^1.2.0. Since it's a transitive dependency, we can not directly update minimist directly.

Going to create a pull request against json5.

**Comment by hencrice** [comment]
Fixed was merged but hasn't been released: https://github.com/json5/json5/commit/741c77de9d49fb639d1ed98f75b31b45192cec67

**Comment by hencrice** [comment]
Released https://github.com/json5/json5/releases/tag/v2.1.2. Need to wait for npm to pick it up

**Comment by clareliguori** [comment]
Fixed in latest dependabot round
