### ISSUE TITLE
Clearly document necessary permissions for workflow

### ISSUE THREAD

**Issue by TigranKhudav** [aws-actions/configure-aws-credentials#460]
Hi I have a this problem on the reusable workflow
![image](https://user-images.githubusercontent.com/78018678/174594098-83c092ad-7aec-4493-9a2b-bdeb821c4458.png)

this is my workflow
![image](https://user-images.githubusercontent.com/78018678/174594392-397095ac-e5ba-4654-b359-434e4aa1cb43.png)

**Comment by imranshaikmuma** [comment]
I am facing the same issue

**Comment by Dgame** [comment]
Solved it somehow by using `@master` instead of `@v1`

**Comment by TigranKhudav** [comment]
@Dgame I tried that, but in vain
I find solution you need to add this `secrets: inherit`
In my case hire
![image](https://user-images.githubusercontent.com/78018678/175501071-26b83f44-6211-4e32-8371-e8e3d60b428b.png)

**Comment by parisnakitakejser** [comment]
i think you need

```yaml
permissions:
  id-token: write
  contents: read
```

Its what i needed in my case.

**Comment by vreddhi** [comment]
> i think you need
> 
> ```yaml
> permissions:
>   id-token: write
>   contents: read
> ```
> 
> Its what i needed in my case.

This worked for me as well

**Comment by peterwoodworth** [comment]
This is now documented better, and there is a helpful message that shows in the workflow logs if it's likely you need to enable this permission in `v3`
