### ISSUE TITLE
Issue overriding default audience value

### ISSUE THREAD

**Issue by Borewit** [aws-actions/configure-aws-credentials#477]
When I specify `audience` 

https://github.com/aws-actions/configure-aws-credentials/blob/34779ed730da18be6e68b2bd0122feff57a542e5/README.md#L126

I get an error that `audience` is an invalid input:

> Warning: Unexpected input(s) 'audience', valid inputs are ['aws-access-key-id', 'aws-secret-access-key', 'aws-session-token', 'aws-region', 'mask-aws-account-id', 'role-to-assume', 'web-identity-token-file', 'role-duration-seconds', 'role-session-name', 'role-external-id', 'role-skip-session-tagging']

**Comment by peterwoodworth** [comment]
Hey @Borewit,

we've made this change pretty recently. Which branch are you using this in? (i.e. what are you inputting for `uses`?) We haven't made a new release with this change yet, but will soon, so if you're using the v1 branch this change won't be in quite yet

**Comment by peterwoodworth** [comment]
The release is out now, so v1 should work now. Let me know if it doesn't
