### ISSUE TITLE
Allow to un-mask AWS Region

### ISSUE THREAD

**Issue by yaldram** [aws-actions/configure-aws-credentials#494]
- At present the aws region is masked out, even if we were to hard-code the region in a command. 
- I am using github actions for deploying a static site to S3 and I need to unmask the aws secrets to see the full S3 website URL.
- Similar to `mask-account-id`, please also consider the option `mask-aws-region`. Thanks

**Comment by yaldram** [comment]
Got my solution if we don't want your aws region to get masked please don't use it as a secret like {{secrets.AWS_REGION}} simply hard code it in our workflow commands.

**Comment by peterwoodworth** [comment]
You got it @yaldram, thanks for following up with the solution!
