### ISSUE TITLE
Reading and passing the masked values

### ISSUE THREAD

**Issue by mma0812** [aws-actions/configure-aws-credentials#497]
I have a use case to use this OIDC configuration, generate the temp credentials, and pass the values to another internal tooling. I thought of reading the temporary credentials caused by this action and passing them on to my internal tool. However, when I read printenv, the desired values are masked. Is there a way to read the actual creds? 

printenv|grep -i 'AWS'
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***

**Comment by peterwoodworth** [comment]
Hey @mma0812, 

We mask the credentials with the [`setSecret` command](https://github.com/actions/toolkit/blob/main/packages/core/README.md), which is ensuring the secret values are masked in logs with no direct workaround I'm aware of

However if you really need to, you can expose the values through [some relatively hacky means.](https://zellwk.com/blog/debug-github-actions-secret/)

If this gets enough attention I suppose we could make it an option for this action to not set these values as secret, but I'd prefer to not create a potentially risky feature like that
