### ISSUE TITLE
##[error]The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.The request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by leo-novu** [aws-actions/configure-aws-credentials#50]
I am receiving:

Configure AWS Credentials
Run aws-actions/configure-aws-credentials@v1
  with:
    aws-access-key-id: ***
    aws-secret-access-key: ***
    aws-region: ***

**##[error]The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.**

- The first run with this access-key-id & aws-secret-access-key worked.  Every consecutive run is failing.
- This same access-key-id & aws-secret-access-key works consistently in circleci
- Tried with aws-actions/configure-aws-credentials@v1.3.2  and received the same results

Config:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

Looks like a problem with: AWS Signature Version 4 Key Signing Errors
https://docs.aws.amazon.com/general/latest/gr/signature-v4-troubleshooting.html

Any suggestions?

**Comment by clareliguori** [comment]
Does the secret access key value have any special characters in it like a slash?  I'm wondering if the Actions SDK this uses doesn't escape values.

**Comment by leo-novu** [comment]
There is one special character between the two and it is a +. Other than that all other characters are either upper or lowercase alphanumeric characters

**Comment by clareliguori** [comment]
I'm only able to reproduce the error you are seeing when the secret access key string I have stored in GitHub secrets does not actually match the correct secret access key value for the given access key ID.  For example, missing a character at the end.

I tried a bunch of combinations of special characters like `fake+secret-access-key/hello/world`, and I'm able to see that they are being plumbed through to the action correctly by GitHub Actions.  I added some debugging to my fork if you want to confirm for your access key.  It confirms that the creds used by the AWS client in the action match the creds from the action inputs.

Example:
```
    - name: Configure AWS credentials
      uses: clareliguori/configure-aws-credentials@debug-requests
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
```

Example run using a fake secret access key value:
https://github.com/clareliguori/configure-aws-credentials/runs/550171988?check_suite_focus=true

```
Does request access key ID match input? true
Does request secret access key match input? true
Does request region match input? true
```

**Comment by PeterKnealeCMRI** [comment]
I believe this also occurs when the generated AWS secret access key starts with a slash. Not sure why this is possible to begin with as its causing issues with quite a bit of tooling

https://stackoverflow.com/questions/30518899/amazon-s3-how-to-fix-the-request-signature-we-calculated-does-not-match-the-s
