### ISSUE TITLE
how do we pass the proxy env address to it ? its fails with connection timeut when we use proxy and system don't have internet access

### ISSUE THREAD

**Issue by Thangarajsubramani** [aws-actions/configure-aws-credentials#504]

**Comment by Thangarajsubramani** [comment]
Error: connect ETIMEDOUT 52.95.18.19:443

**Comment by peterwoodworth** [comment]
Hey @Thangarajsubramani, there is currently no way to set the proxy unfortunately. However, we're working on a [PR](https://github.com/aws-actions/configure-aws-credentials/pull/246) that should be merged soon that will allow you to configure your proxy. Be on the lookout for our next release, hopefully our next release will be next week and that it will have this feature implemented!
