### ISSUE TITLE
short issue description

### ISSUE THREAD

**Issue by tongzcomradez** [aws-actions/configure-aws-credentials#522]
### Describe the feature

set credential with profile name

### Use Case

i use this for automation terraform and i need to fix profile name in tf file 
but your lib cant dynamic my profile
<img width="331" alt="Screen Shot 2565-10-13 at 10 59 54" src="https://user-images.githubusercontent.com/19509697/195496107-e6086b15-7581-4e30-a5aa-4d7a88d44372.png">

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
Thanks for submitting this request! I think it overlaps with #112, please be sure to give your support on that issue!
