### ISSUE TITLE
AWS_SECRET_ACCESS_KEY starting with a "/" becomes malformed (SignatureDoesNotMatch) on Windows only

### ISSUE THREAD

**Issue by svollath** [aws-actions/configure-aws-credentials#528]
### Describe the bug

I'm using aws-actions/configure-aws-credentials@v1 to update route53 DNS records for testing with github action runners.
The code in regard to that specific step is identical over tests using different OS images, where updating DNS records on:

- ubuntu-latest (passes)
- macos-latest (passes)
- windows-latest (fails)

On Windows, all aws-cli commands fail with:

`An error occurred (SignatureDoesNotMatch) when calling the ChangeResourceRecordSets operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`

This was really hard to debug, since the given `aws-secret-access-key` works on Linux and MacOS. It also worked on a local Windows10 installation with aws-cli-2.8.0, when the secret was exported using Windows `setx` env var.

Finally I was able to reproduce that error locally, when I gave the correct `aws-access-key-id`, but a malformed `aws-secret-access-key`.
Then it was proven, by creating new keys - where the `aws-secret-access-key` doesn't start or contain a "/".

From quickly looking at your code, it seems it's up to the respective AWS SDK to create the env vars - so guess this is where the secret becomes malformed ...

### Expected Behavior

When I hold valid credentials provided by AWS within Github Action Secrets, those should be working on all Github Action Runners Images offered.
If there are restrictions on special characters for secrets, this should be documented - and aws-actions/configure-aws-credentials@v1 should error out - just as with e.g. wrong credentials.

### Current Behavior

aws-actions/configure-aws-credentials@v1 is successfully configured with a `aws-secret-access-key` starting with a "/", but aws-cli on Windows later fails to auth/request anything.
No such restriction mentioned in docs for configure-aws-credentials or "Best practices for managing AWS access keys".
Finally it's working for Linux and MacOS, but fails for Windows runners.

### Reproduction Steps

I'm providing `aws-access-key-id` `aws-secret-access-key` for aws-actions/configure-aws-credentials@v1 via github action secrets.
aws-actions/configure-aws-credentials@v1 configuration step works fine on al OS images.
Using the same code to change DNS records with aws-cli over ubuntu-latest, macos-latest and windows-latest gha images.
But also `aws sts get-caller-identity`command on windows-latest would give the same output:
`An error occurred (SignatureDoesNotMatch) when calling the ChangeResourceRecordSets operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`

### Possible Solution

Since I manually proved that a secret-key, starting with a "/" works fine on Windows and aws-cli, you should fix `aws-secret-access-key` to not become malformed by (I guess) AWS SDK (´setx`) var handling.

**Comment by kellertk** [comment]
Hi! You're right in that the SDKs and CLI can sometimes have problems with secret access keys that have special characters on some operating systems. Check out this comment on the AWS CLI repo: https://github.com/aws/aws-cli/issues/602#issuecomment-648952330

I'm going to try and reproduce this to make sure, but I think this is a larger issue related to credential handling in the SDKs.

**Comment by kellertk** [comment]
Here's the results of my testing trying to do a STS `GetCallerIdentity` and the equivalent of `aws s3 ls` on various installations. I exported the credentials into environment variables, or on GHA via repository secrets:

| Operating System | Tool | Result |
| ------------------ | ---- | ------ |
| Local macos 12.3.1 | aws-cli 2.7.31 | ✅ |
| Local macos 12.3.1 | aws-sdk-js-v3 3.190.0 | ✅ |
| Local macos 12.3.1 | boto3 1.24.93 | ✅ |
| Local Windows 10 20H2 PS | aws-sdk-js-v3 3.188.0 | ✅ |
| Local Windows 10 20H2 PS | aws-cli 2.3.7 | ✅ |
| Local Windows 10 20H2 PS | boto3 1.24.93 | ✅ |
| Local Windows 10 20H2 cmd | aws-sdk-js-v3 3.188.0 | ✅ |
| Local Windows 10 20H2 cmd | aws-cli 2.3.7 | ✅ |
| Local Windows 10 20H2 cmd | boto3 1.24.93 | ✅ |
| GHA ubuntu-latest (@v1) | aws-cli 2.8.0 | ✅ |
| GHA macos-latest (@v1) | aws-cli 2.8.1 | ✅ |
| GHA windows-latest (@v1) | aws-cli 2.8.2 | ✅ |
| GHA windows-2019 (@v1) | aws-cli 2.8.2 | ✅ |
| GHA ubuntu-latest (@v1-node16) | aws-cli 2.8.2 | ✅ |
| GHA macos-latest (@v1-node16) | aws-cli 2.8.2 | ✅ |
| GHA windows-latest (@v1-node16) | aws-cli 2.8.2 | ✅ |
| GHA windows-2019 (@v1-node16) | aws-cli 2.8.2 | ✅ |

I tried to get this to break, but I just couldn't. Are there any other steps you have that will reliably reproduce this issue?
