### ISSUE TITLE
Changes are not being published

### ISSUE THREAD

**Issue by sindrig** [aws-actions/configure-aws-credentials#531]
### Describe the bug

After looking at https://github.com/aws-actions/configure-aws-credentials/issues/521 and seeing that @actions/core has already been updated on master, I saw that [the package action](https://github.com/aws-actions/configure-aws-credentials/actions/workflows/package.yml) has been broken for some time. This means that changes to any of the javascript code never make it to dist.

### Expected Behavior

Code that reaches master should be packaged automatically

### Current Behavior

The package action fails with this error:

```
 remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: 3 of 3 required status checks are expected. At least 1 approving review is required by reviewers with write access.        
To https://github.com/aws-actions/configure-aws-credentials
 ! [remote rejected] HEAD -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/aws-actions/configure-aws-credentials'
Error: Process completed with exit code 1.
```

[Example run](https://github.com/aws-actions/configure-aws-credentials/actions/runs/3245630680/jobs/5323409444)

### Reproduction Steps

Not applicable - is broken on master

**Comment by peterwoodworth** [comment]
Thanks for reporting this @sindrig, this occurred when we updated the branch protection rules recently (code has to be merged in a PR and cannot be pushed directly). We're working on figuring out the best permanent solution, but in the meantime we can probably do this manually.

**Comment by renperez-cpi** [comment]
@peterwoodworth please update us when this is merged. thank you

**Comment by peterwoodworth** [comment]
@renperez-cpi The latest changes have been merged to master 🙂
