### ISSUE TITLE
Assuming Role in different AWS Account

### ISSUE THREAD

**Issue by bennettl** [aws-actions/configure-aws-credentials#54]
We have keys , secret access key for iAM user (deployer) in one account, want to assume role in another account (devops).

Got this error

##[error]User: arn:aws:iam::***:user/deployer is not authorized to perform: sts:TagSession on resource: arn:aws:iam::***:role/devops

**Comment by clareliguori** [comment]
In addition to allowing `sts:AssumeRole` in your role's trust policy, you also need to allow `sts:TagSession`
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html#id_session-tags_permissions-required
