### ISSUE TITLE
Github Action `set-output` command is deprecated

### ISSUE THREAD

**Issue by riyaolin** [aws-actions/configure-aws-credentials#540]
### Describe the bug

Got this warning when using this github action:
```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. 

For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

### Expected Behavior

No warning.

### Current Behavior

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. 

### Reproduction Steps

Any workflows use this github action can see this warning.

### Possible Solution

The bot had upgraded core to 0.10.0 which should fix the warning. Please make a new release to solve the issue.
Reference: `https://github.com/aws-actions/configure-aws-credentials/commit/499b4f9c352dada68767fbd591c1c7d02f4cc555`

**Comment by gauntface** [comment]
This should be fixed by https://github.com/aws-actions/configure-aws-credentials/commit/1cb4968956a6a7aa09e9b7808b539e4df883f610

This is my understanding based on the info from: https://github.com/actions/toolkit/issues/1212#issuecomment-1281352626

**Comment by kellertk** [comment]
Hi there, please see #521
