### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by donfirst** [aws-actions/configure-aws-credentials#550]
### Describe the feature

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: aws-actions/configure-aws-credentials

### Use Case

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: aws-actions/configure-aws-credentials

### Proposed Solution

ugrade to node 16

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by nantiferov** [comment]
Duplicates https://github.com/aws-actions/configure-aws-credentials/issues/489

There is a tag already with node16 https://github.com/aws-actions/configure-aws-credentials/issues/489#issuecomment-1278145876

**Comment by kellertk** [comment]
Please see the notice at the top of README.md
