### ISSUE TITLE
Could not load credentials from any providers for a PR from a fork

### ISSUE THREAD

**Issue by spcaipers-arm** [aws-actions/configure-aws-credentials#564]
### Describe the bug

Hello,

I am facing an issue where I am getting:
`Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers`

Only when the GitHub actions are triggered by a PR from a fork.
I am *NOT* using secrete. 

Snippet:
`jobs:
  ci_test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
 
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

     - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{ env.AWS_ASSUME_ROLE }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}`

The `env.AWS_ASSUME_ROLE` and `env.AWS_DEFAULT_REGION` are correctly populated!

**The workflow works fine if a PR is opened from an internal branch!!**

Any idea?

        
        

### Expected Behavior

The actions should be able to get the creds.

### Current Behavior

Failing in getting creds.

### Reproduction Steps

1. Fork a repo
2. Create a PR from the fork to the upstream repo.

**Comment by activescott** [comment]
Same issue here. A run with debug logging (that doesn't appear to have anything helpful) is at https://github.com/activescott/serverless-aws-static-file-handler/actions/runs/3662018526/jobs/6190926634#step:6:18

An example run where this same unmodified workflow ran successfully using a PR from a non-forked PR is at https://github.com/activescott/serverless-aws-static-file-handler/actions/runs/3661980337/jobs/6190716806#step:6:1

**Comment by kellertk** [comment]
This is not a bug in this action - it's how GitHub Actions works for OIDC. 

Even requesting a JWT for OIDC requires the action to have the `id-token: write` permission. See the [GitHub docs](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings) on this. Pull requests from public forks though, [don't have this permission](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token).
