### ISSUE TITLE
MIssing "ListDeployments" permissions not handled correctly

### ISSUE THREAD

**Issue by fleaz** [aws-actions/configure-aws-credentials#580]
### Describe the bug

When "ListDeployments" is missing from the IAM permissions, the action doesn't handle the received error and thinks a deployment is currently running and enters the "wait 15s and try again" loop

### Expected Behavior

The action should catch the error and exit.

### Current Behavior

![2022-11-18T15:38:32,311213841+01:00](https://user-images.githubusercontent.com/2489598/202730251-b175d81f-ecf0-40c8-a665-e10f6b3bb7d3.png)

### Reproduction Steps

Remove "ListDeployments" from IAM and start a deployment.

### Possible Solution

The error should be catched and the action should exit because there is no point in trying again.

**Comment by peterwoodworth** [comment]
@fleaz are you sure this is part of running this action, and not a step you've written after this action is ran? If your workflow needs to perform the `ListDeployments` action with the role you are assuming, that is naturally something that you'll need to configure on your role.

**Comment by fleaz** [comment]
Oh damnit, my bad! I opened the issue in the wrong repository 🙈 
Probably had to many tabs open. Sorry for the noise! :)
