### ISSUE TITLE
Set-output command is deprecated

### ISSUE THREAD

**Issue by genarocolonel** [aws-actions/configure-aws-credentials#601]
### Describe the bug

The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### Expected Behavior

I am expecting echo `"environment=development" >> $GITHUB_OUTPUT` instead of `echo "::set-output name=environment::development"`.

### Current Behavior

Current behavior is using old `set-output`, for example `echo "::set-output name=environment::development"`

### Reproduction Steps

Using `aws-actions/configure-aws-credentials@v1` in our GitHub Actions script.

### Possible Solution

Use `"environment=development" >> $GITHUB_OUTPUT` instead of `echo "::set-output name=environment::development"`.

**Comment by genarocolonel** [comment]
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/103074659/206851637-5069cd30-8068-479a-a9e7-a59fc9b0b0c4.png">

**Comment by levivannoort** [comment]
related issue on the dependency: https://github.com/actions/toolkit/issues/1218

**Comment by QuintinWillison** [comment]
Example [here](https://github.com/ably/ably-asset-tracking-android/actions/runs/3696426041):

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: **aws-actions/configure-aws-credentials@v1**, ably/sdk-upload-action@v1

Please can you consider fixing this soon as it looks like the grace period for full migration to Node.js 16 in workflows is about 6 months (summer 2023, according to the blog post mentioned in the log output quoted above).

GitHub's core family of actions made this change as a `major` (breaking) release from `v2` to `v3` over 6 months ago - e.g.:

- https://github.com/actions/checkout/releases/tag/v3.0.0
- https://github.com/actions/upload-artifact/releases/tag/v3.0.0

**Comment by bendrucker** [comment]
I've left a comment in that issue, `@actions/core` has supported this and is backwards compatible as of ~2 months ago. I can work on a PR to fix this.

**Comment by bendrucker** [comment]
Turns out this is fixed in main and just not released.

https://github.com/aws-actions/configure-aws-credentials/issues/521

Switching to `@v1-node16` resolves it and should generally be the default for most users until `v2`.
