### ISSUE TITLE
Update set-output and node-js 

### ISSUE THREAD

**Issue by rsharma02-entrata** [aws-actions/configure-aws-credentials#622]
### Describe the bug

Node.js 12 actions are deprecated. For more information see: [Link to GitHub Doc](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

Similarly for set-output

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: [link](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

### Expected Behavior

There should not be any warning 

### Current Behavior

Getting warnings related to the same

### Reproduction Steps

![image](https://user-images.githubusercontent.com/90019678/211258288-02c03963-b887-4e53-ac73-1f66028ef16b.png)

**Comment by moritzheiber** [comment]
https://github.com/aws-actions/configure-aws-credentials/issues/489#issuecomment-1278145876

**Comment by rsharma02-entrata** [comment]
ok thanks @moritzheiber 
Got the Solution.
