### ISSUE TITLE
Enable node 16 

### ISSUE THREAD

**Issue by rsharma02-entrata** [aws-actions/configure-aws-credentials#660]
### Describe the feature

Can you Enable node 16 as we are getting warnings for this 

### Use Case

Can you Enable node 16 as we are getting warnings for this 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by alexgwolff** [comment]
`uses: aws-actions/configure-aws-credentials@v1-node16`

**Comment by bdo** [comment]
Duplicate of #489

**Comment by peterwoodworth** [comment]
Yes, please see the linked issue #489. A more stable long term solution is in the works. Thanks!
