### ISSUE TITLE
Warning: The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by kirillg10** [aws-actions/configure-aws-credentials#668]
### Describe the bug

My workflow works great using this action, the only thing is the error below being displayed:

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### Expected Behavior

No errors

### Current Behavior

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### Reproduction Steps

Run a workflow using aws-actions/configure-aws-credentials@v1

**Comment by lrstanley** [comment]
Believe this is already fixed in main (and has been for a bit), just not released yet.

**Comment by kellertk** [comment]
Please see https://github.com/aws-actions/configure-aws-credentials/issues/489#issuecomment-1278145876
