### ISSUE TITLE
All AWS OIDC integrations will break before 13th April 2031

### ISSUE THREAD

**Issue by n1ngu** [aws-actions/configure-aws-credentials#669]
### Describe the bug

A massive complain about
```
An error occurred (InvalidIdentityToken) when calling the AssumeRoleWithWebIdentity operation: OpenIDConnect provider's HTTPS certificate doesn't match configured thumbprint
```
errors is to be expected before the intermediate certificate used by DigiCert to issue *.actions.githubusercontent.com TLS certificate is expired.

After that, the issue will chronically repeat each time
- your CA rotates the operative intermediate certificate (nearest deadline 13th Apr 2031)
- your CA rotates their root certificate (nearest deadline 10th Nov 2031)
- you change your CA of choice (die at your will)

### Expected Behavior

I'd expect not being impacted by DigiCert rotating their operative cert nor GitHub switching to whatever CA they liked.

### Current Behavior

This is because AWS requires fingerprinting CA intermediate certificate. Fingerprinting end certificates also works but breaks at an even higher frequency. Unlike the sensible thing to do, AWS does not validate the TLS cert with a pre-trusted root certificate list but with this fingerprint which can't be updated by OIDC users before it breaks. IMHO this is an AWS issue.

### Reproduction Steps

Wait until 13th April 2031 and see how everything is already broken.

Alternatvely: deploy a new TLS certificate for the https://token.actions.githubusercontent.com site signed by an alternative CA, LetsEncrypt for example. See everything break.

Alternatively: see all past events of this issue!

### Possible Solution

I think there is enough evidence so that big players can reach AWS and tell them to stop the nonsense.

If that does not work, GitHub could host their JWKS in AWS S3 instead of https://token.actions.githubusercontent.com/.well-known/jwks. Other OIDC consumers should be unaffected.

If that is not an option, GitHub could depoy a self-signed never-expiring TLS cert and don't rotate it ever again. But I hope this is neither an option.

Otherwise, the only thing left for GitHub to do would be putting on hold new certs from DigiCert, publishing their fingerprints, tell users to subscribe to that and update their identity provider on AWS web console, and deploy live the new certificate only in the last possible minute.

### Additional Information/Context

- Past events of this issue https://github.com/aws-actions/configure-aws-credentials/issues/357, https://github.com/aws-actions/configure-aws-credentials/issues/579
- Equivalent GitLab issue https://gitlab.com/gitlab-org/gitlab/-/issues/392713
- Bitbucket incident after a certificate rotation on late June 2022 https://bitbucket.status.atlassian.com/incidents/3s2tb3329ftd . Old certificate was restored until it expired. Then, any integration not fingerprinting the intermediate cert... broke again.
- Unanswered SO question on how to canonically solve this https://stackoverflow.com/questions/72805530/how-to-not-thumbprint-aws-oidc-provider-rotating-certificate
- Lots of similar issues for minor projects https://github.com/calidae/terraform-aws-bitbucket-oidc/issues/1 https://github.com/terraform-module/terraform-aws-gitlab-oidc-provider/issues/25 https://gitlab.com/guided-explorations/aws/configure-openid-connect-in-aws/-/issues/3

**Comment by kellertk** [comment]
Hi there - thanks for this issue. It's detailed and well-researched.

As it turns out, the team responsible for maintaining this action is not the same team within AWS that maintains IAM. That doesn't really matter; I'm only mentioning it because I will have to reach out to them internally for their take on this. You might not see an update directly from the IAM team here because they don't work on GitHub, but I'll certainly relay any information they give me. Luckily this isn't going to break tomorrow, but it will be a bit like Y2K was supposed to be if we wait too long on this.

**Comment by kellertk** [comment]
Internal P82323250

**Comment by n1ngu** [comment]
> Luckily this isn't going to break tomorrow

Sure thing, no hurry! Yet, note the deadline for OIDC providers other than GitHub might be much shorter. E.g. GitLab OIDC will stop working before 2025 https://gitlab.com/gitlab-org/gitlab/-/issues/392713

**Comment by kellertk** [comment]
This was acknowledged by the IAM team as known and in progress. I have no updates to share other than this will be fixed by 2031. Rather than leaving issue open for 7 or more years, I'm going to close this for now. Thanks for the report!

**Comment by n1ngu** [comment]
Already broke because github is deploying two different DigiCert intermediate certificates.

https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/

**Comment by jarnohenneman** [comment]
@kellertk any updates on the issue?

Personally not a huge fan of the answer fixed by 2031 - we are not discussing an AWS beta feature here.

**Comment by n1ngu** [comment]
@jarnohenneman last words on the matter were https://github.com/aws-actions/configure-aws-credentials/issues/357#issuecomment-1613427884

> The path forward to making this a better experience involves changing how IAM works, or how GitHub is managing their certificates, or both. I don't have any information to share today other than the IAM team is aware of this sharp edge and we want to make it better in the future. If I have anything to announce there, I'll share that as soon as possible.

So I don't think there is anything to do besides subscribing to these issues and github blog and stay alert to OIDC integrations recurringly breaking.

**Comment by kellertk** [comment]
@jarnohenneman This issue is to track the fact that GitHub's certificate chain has an expiration date, not that GitHub has been presenting different intermediate thumbprints lately. Luckily, the IAM team is working on some changes that will fix both issues, but I don't have any information that I can share outside of that.

**Comment by kellertk** [comment]
Please see https://github.com/aws-actions/configure-aws-credentials/issues/357#issuecomment-1626357333, which should resolve this issue.
