### ISSUE TITLE
OIDC credential unable to use in other steps

### ISSUE THREAD

**Issue by macbash** [aws-actions/configure-aws-credentials#684]
### Describe the bug

Hi Team,

im assuming an OIDC role using "aws-actions/configure-aws-credentials" which works fine, but while I need the AWS creds like AWS_ACCESS_KEY_ID, SESSION_TOKEN, I have tried to use the in other steps like ${{env. AWS_ACCESS_KEY_ID }} in docker build-args which isn't working, is there any correct way of getting the credentials and passing to docker build ?

### Expected Behavior

Docker build to get some files from s3 as part of the process, its has to work, currently its failed due to unable to locate credentials

### Current Behavior

failure in docker build

### Reproduction Steps

how to get the creds from aws-actions/configure-aws-credentials and pass to other steps like docker build

**Comment by yoavniran** [comment]
exactly the same issue im running into the last couple of days. 
I'd like to pass the credentials into my docker build. Really hoping that's possible

**Comment by dasoto** [comment]
I haven't tested as build time but at least when you run the container you can pass the env variables on the docker run command:
```
--env $AWS_ACCESS_KEY_ID
--env $AWS_DEFAULT_REGION
--env $AWS_SECRET_ACCESS_KEY
--env $AWS_SESSION_TOKEN
```

**Comment by yoavniran** [comment]
yes. Im happy to say that this worked:

Dockerfile:


```
.
.
.
FROM base as deps

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_SESSION_TOKEN

#Install AWS CLI
RUN apt-get update && \
    apt-get install -y \
        python3 \
        python3-pip \
        python3-setuptools \
        groff \
        less \
    && pip3 install --upgrade pip \
    && apt-get clean

RUN pip3 --no-cache-dir install --upgrade awscli

RUN aws configure set region us-east-1
RUN aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
RUN aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
RUN aws configure set aws_session_token $AWS_SESSION_TOKEN
```

GH Job:

```yaml
.
.
.
run: |
          docker build \
          --build-arg AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }} \
          --build-arg AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }} \
          --build-arg AWS_SESSION_TOKEN=${{ env.AWS_SESSION_TOKEN }} \
          -t $IMAGE_TAG .
```

**Comment by peterwoodworth** [comment]
Yes, this looks accurate @yoavniran. I'm curious how the attempts that failed for you two were configured?
