### ISSUE TITLE
DOCS: add note about case sensitivity of username

### ISSUE THREAD

**Issue by AdisonCavani** [aws-actions/configure-aws-credentials#686]
### Describe the issue

I spent a good amount of time debugging why am I getting: `Not authorized to perform sts:AssumeRoleWithWebIdentity`.
It turns out when configuring trust policy I used `repo:adisoncavani/*` instead of `repo:AdisonCavani/*`.

I think it might be a good idea to add a note, about case sensitivity when configuring trust policy.

**Comment by peterwoodworth** [comment]
I think it would make most sense to add this note to the parameters as a new description property in our sample CloudFormation template. PR is welcome like @mifi said 🙂
