### ISSUE TITLE
Describe any breaking changes from v1 to v2

### ISSUE THREAD

**Issue by jensenbox** [aws-actions/configure-aws-credentials#691]
### Describe the issue

Thanks for making the new release from v1 to v2 but I think we are missing documentation on what areas could break.

I would love to do the upgrade but would love to see what I need to be on the watch for if I make the update. Is the only change the node version? If so then the docs should state that. If there are other things that could affect the behavior those should be stated as well.

Thanks again!

**Comment by peterwoodworth** [comment]
This only impacts the node version - the more interesting update is going to come when we release v3 which makes use of JS SDK v3. For now though, you can feel comfortable upgrading. Thanks for the feedback, I've created a PR, let me know if you think the PR properly addresses this issue https://github.com/aws-actions/configure-aws-credentials/pull/692
