### ISSUE TITLE
issue with github oidc role-to-assume s3 permission

### ISSUE THREAD

**Issue by sibelius** [aws-actions/configure-aws-credentials#698]
### Describe the bug

fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

### Expected Behavior

it should work

### Current Behavior

fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

### Reproduction Steps

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::1234567890:role/DeployRole
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync ./out s3://example.com

### Possible Solution

Fix role permission

### Additional Information/Context

This is how I deploied github oidc to aws using aws-cdk

```jsx
export class OwnerGithubOidcStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const provider = GithubActionsIdentityProvider.fromAccount(this, 'GithubProvider');

    const deployRole = new GithubActionsRole(this, 'DeployRole', {
      provider,
      owner: 'owner',
      repo: '*',
      roleName: 'DeployRole',
      description: 'This role deploys stuff to AWS',
      maxSessionDuration: cdk.Duration.hours(2),
    });
  }
}
```

**Comment by peterwoodworth** [comment]
Did you add permissions to the role? Based on your CDK code it looks like you left out the permissions to grant to the role. It looks like `GithubActionsRole` extends [`iam.Role`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam-readme.html#overview), so you should be able to use `addManagedPolicy()` or `addToPolicy()`. An example from this custom construct's docs shows this in action:

```ts
// You may also use various "add*" policy methods!
// "AdministratorAccess" not really a good idea, just for an example here:
deployRole.addManagedPolicy(iam.ManagedPolicy.fromAwsManagedPolicyName('AdministratorAccess'));
```
