### ISSUE TITLE
Best practices solution integration github actions with nektos/act (a local github runner)

### ISSUE THREAD

**Issue by elasticdotventures** [aws-actions/configure-aws-credentials#718]
### Describe the feature

https://github.com/nektos/act

Nektos act is a local runner for github actions.   Using act for local development testing can be a huge productivity win by not having to wait for a remote runner to be allocated.  Act has a local --watch feature which will automatically trigger on code changes and works exceptionally well in a vscode workflow. 

### Use Case

What are best practices/guidance how to use aws-actions/configure-aws-credentials for self hosted runners in both a local & remote example.   

We are principally a python shop and use the poetry package manager with code artifact to access private internal packages required during the build/test stages.   

### Proposed Solution

TBD. 

### Other Information

We also use ECR, and it would be nice if there was a way to prevent our local development workflows from being able to push directly to AWS ECR or trigger any CI/CD processes.    

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
> What are best practices/guidance how to use aws-actions/configure-aws-credentials for self hosted runners in both a local & remote example.

I don't think using this action should differ regardless of how the runner is hosted. I'm not really familiar with `nektos/act`, though I doubt there's anything special you'd have to know when using this action on runners configured with that tool.

> We also use ECR, and it would be nice if there was a way to prevent our local development workflows from being able to push directly to AWS ECR or trigger any CI/CD processes.

If different workflows are doing different things in different environments, I'd recommend configuring the permissions of the entities at play to ensure a test environment cannot impact a prod environment for instance
