### ISSUE TITLE
Signature calculation fails

### ISSUE THREAD

**Issue by nicolaevladescu** [aws-actions/configure-aws-credentials#72]
Hi.

I have a github workflow in which i use 2 sets of credentials coming from secrets. Both are just key, secret and region, no assume roles etc.

I run `aws-actions/configure-aws-credentials@v1` with the first set of access_key_id+secret_key, then do a ECR login, docker build and push and then ECR logout all being successful.

After that i run `aws-actions/configure-aws-credentials@v1` with the second set of access_key_id+secret_key which runs successfully also and then try to do a `sts get-calller-identity` or `s3 ls` but get the same error on both:

```
An error occurred (SignatureDoesNotMatch) when calling the GetCallerIdentity operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```

So to debug i removed everything except the call with the second set of credentials, and now i get the error on the action level, which used to go through without error when i was doing the ECR stuff first.
```
Run aws-actions/configure-aws-credentials@v1

##[error]The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```

P.S. I tested the second pair of credentials locally on my pc with the same `python` and `awscli` versions and i was able to run `sts get-calller-identity` without any problems.

**Comment by clareliguori** [comment]
Hi @nicolaevladescu , I just released a possible fix for this, can you retry your action?  If it's still giving that error, can you paste an example workflow file?

**Comment by nicolaevladescu** [comment]
Hi.

I could not reproduce anymore, seems fixed!
