### ISSUE TITLE
Add notes to documentation about Enterprise

### ISSUE THREAD

**Issue by juliusoh** [aws-actions/configure-aws-credentials#727]
### Describe the bug

I have
`      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: "TerraformPlan"
`

It throws an error

Error: No OpenIDConnect provider found in your account for https://github.MYORG.net/_services/token

### Expected Behavior

I expect it to successfully assume role. OIDC provider and Role was successfully created in AWS.

### Current Behavior

The error is thrown

### Reproduction Steps

Create OIDC provider for GIthub enterprise account

**Comment by funes79** [comment]
I have a similar issue.  I have a setup where the IAM role was correctly working. Then today it throw the error message.
Not sure if this is kind of a temporary outage, https://www.githubstatus.com/ shows everything green now, I tried to rerun the flow with a newer version (v2), same result.

**Comment by kchandra548** [comment]
@juliusoh As you are using GHES instance, by default OIDC endpoints are internal and not accessible from outside. So you need to expose following endpoints to the internet(public)
https://github.myorg.net/_services/token/.well-known/openid-configuration
https://github.myorg.net/_services/token/.well-known/jwks

**Comment by peterwoodworth** [comment]
Good catch @kchandra548, the enterprise OIDC endpoint is different than normal. See the documentation on GitHub [here](https://docs.github.com/en/enterprise-server@3.9/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#adding-the-identity-provider-to-aws) on how to configure your identity provider when using Enterprise Server

**Comment by peterwoodworth** [comment]
Added short note about enterprise https://github.com/aws-actions/configure-aws-credentials#note-about-ghes
