### ISSUE TITLE
it does not support the credential_process

### ISSUE THREAD

**Issue by June3Ningxu** [aws-actions/configure-aws-credentials#728]
### Describe the bug

In some situation, we want to get the AK/SK from an external process 
but this action  does not support it

by the process, it can output like that
{
    "Version": 1,
    "AccessKeyId": "an AWS access key",
    "SecretAccessKey": "your AWS secret access key",
    "SessionToken": "the AWS session token for temporary credentials", 
    "Expiration": "RFC3339 timestamp for when the credentials expire"
}  
you can also refer to the documents.
https://docs.aws.amazon.com/sdkref/latest/guide/feature-process-credentials.html

so please help to check it
thank you

### Expected Behavior

it can support the credential_process

### Current Behavior

it does not support the credential_process

### Reproduction Steps

N/A

**Comment by peterwoodworth** [comment]
Could you please explain how this might be useful? I've never used `credential_process` - on first glance looking at the documentation I'm not sure how this action would work together with that feature
