### ISSUE TITLE
github actions assume role with web identity gives security token is invalid

### ISSUE THREAD

**Issue by shreera1** [aws-actions/configure-aws-credentials#743]
### Describe the bug

I have the following code in the workflow file
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  tf_code_check:
    name: Kaniko dockerfile
    runs-on: [self-hosted, aws]
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-duration-seconds: 3800

I have configured aws iam role according to the article: https://aws.amazon.com/blogs/security/use-iam-roles-to-connect-github-actions-to-actions-in-aws/

When I check the aws cloud trail logs, I am getting the temporary credentials and it fails almost immediately. Below is the json from cloud trail log

JSON view
{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "WebIdentityUser",
        "principalId": "arn:aws:iam::123456789:oidc-provider/token.actions.githubusercontent.com:sts.amazonaws.com:repo:org/repo:ref:*",
        "userName": "repo:org/repo:ref:*",
        "identityProvider": "arn:aws:iam::123456789:oidc-provider/token.actions.githubusercontent.com"
    },
    "eventTime": "2023-06-12T15:35:16Z",
    "eventSource": "sts.amazonaws.com",
    "eventName": "AssumeRoleWithWebIdentity",
    "awsRegion": "us-west-2",
    "sourceIPAddress": "xxx.xxx.xxx.xxx",
    "userAgent": "aws-sdk-nodejs/2.1386.0 linux/v16.16.0 configure-aws-credentials-for-github-actions promise",
    "requestParameters": {
        "roleArn": "arn:aws:iam::123456789:role/gh-action-sandbox",
        "roleSessionName": "githubactor_5245548963",
        "durationSeconds": 3800
    },
    "responseElements": {
        "credentials": {
            "accessKeyId": "A***",
            "sessionToken": "IQ***",
            "expiration": "Jun 12, 2023, 4:38:36 PM"
        },
        "subjectFromWebIdentityToken": "repo:org/repo:ref:*",
        "assumedRoleUser": {
            "assumedRoleId": "A**:githubactor_5245548963",
            "arn": "arn:aws:sts::123456789:assumed-role/gh-action-sandbox/githubactor_5245548963"
        },
        "provider": "arn:aws:iam::123456789:oidc-provider/token.actions.githubusercontent.com",
        "audience": "sts.amazonaws.com"
    },
    "requestID": "***-**-**-**-***",
    "eventID": "***-**-**-**-***",
    "readOnly": true,
    "resources": [
        {
            "accountId": "123456789",
            "type": "AWS::IAM::Role",
            "ARN": "arn:aws:iam::123456789:role/gh-action-sandbox"
        }
    ],
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "recipientAccountId": "123456789",
    "eventCategory": "Management",
    "tlsDetails": {
        "tlsVersion": "TLSv1.2",
        "cipherSuite": "ECDHE-RSA-AES128-GCM-SHA256",
        "clientProvidedHostHeader": "sts.us-west-2.amazonaws.com"
    }
}

### Expected Behavior

Passing action when configuring aws credentials in the workflow

### Current Behavior

Error: The security token included in the request is invalid

### Reproduction Steps

NA

**Comment by peterwoodworth** [comment]
Can you share the logs of the action run, as well as your full workflow file? Which step in your workflow is failing with that message?

**Comment by shreera1** [comment]
Run aws-actions/configure-aws-credentials@v[2](https://<repo>/actions/runs/5245829356/jobs/9473825857#step:4:2)
  with:
    role-to-assume: ***
    aws-region: ***
    role-duration-seconds: 3800
    role-session-name: shreera1_5245829356
    audience: sts.amazonaws.com
Setting proxy from environment: http://proxy:port
(node:665381) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
Error: The security token included in the request is invalid

The workflow file is below: It fails in configuring aws credentials step
name: Terraform CI workflow 

on:
  workflow_call:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:

  ci:
    name: CI dockerfile and terraform
    runs-on: [self-hosted, aws]
    defaults:
      run:
        shell: bash
        working-directory: infra/ci     

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository}}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setting up env
        id: env_setup  
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}   
        run: |
            echo "$GITHUB_CONTEXT"
        continue-on-error: true
  

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-duration-seconds: 3800
          role-session-name: ${{ github.actor }}_${{ github.run_id }}

**Comment by peterwoodworth** [comment]
STS throws vague errors (I believe intentionally), so sorry for not being able to provide clear direction. Here's a couple things I recommend doing that could help

- Check the trust policy of the role you're trying to assume to make sure it can be assumed through OIDC. Please post it here if you can't find anything wrong with it and the next step doesn't work
- Try running this on a GitHub hosted runner. It's possible the self hosted runner is preconfigured with conflicting environment variables, so attempting to run this on a GitHub hosted runner would ensure that's not the issue.

**Comment by peterwoodworth** [comment]
Also, you would be getting a different kind of error when switching the event that invokes this action, likely due to the `sub` of the OIDC claim changing. I assume you meant `pull_request` instead of `push_request`, and the [sub claim will change](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#filtering-for-pull_request-events) in that case, which means you'd have to account for this in your trust policy

**Comment by shreera1** [comment]
Thanks @peterwoodworth. The second point you made above was correct. I had conflicting credentials in the github self-hosted runner. Thanks.
