### ISSUE TITLE
Intermittent failure on this error:  OpenIDConnect provider's HTTPS certificate doesn't match configured thumbprint

### ISSUE THREAD

**Issue by JasonIamAUnixAdmin** [aws-actions/configure-aws-credentials#757]
### Describe the bug

 Not a consistent error. 
On a GHA with 14 different steps 2 fail with `OpenIDConnect provider's HTTPS certificate doesn't match configured thumbprint` all use the same role to do work. 

Re-running will eventually clear the error

This also happens on GHA with a single step so not related to volume of requests.

### Expected Behavior

Not getting HTTPS errors

### Current Behavior

Intermitent failures with the above error 

![Screen Shot 2023-06-28 at 7 02 11 AM](https://github.com/aws-actions/configure-aws-credentials/assets/10491503/4b12c946-2377-4fa8-bd7a-17e029174d51)

### Reproduction Steps

Run a job and get this error. Is intermittent. Like a host in a clusters clock is off far enough to fail a cert.

**Comment by n1ngu** [comment]
See #669

**Comment by n1ngu** [comment]
See #357 as well

**Comment by JasonIamAUnixAdmin** [comment]
Based on above links the error message might include a hint like "Please check thumbprint"

**Comment by mrparkers** [comment]
For anyone that uses Terraform to configure their OIDC provider in AWS, this snippet may be helpful:

```hcl
data "tls_certificate" "github" {
  url = "https://token.actions.githubusercontent.com/.well-known/openid-configuration"
}

resource "aws_iam_openid_connect_provider" "github" {
  url = "https://token.actions.githubusercontent.com"

  client_id_list = [
    "sts.amazonaws.com",
  ]

  thumbprint_list = [
    for c in data.tls_certificate.github.certificates : c.sha1_fingerprint
  ]
}
```

**Comment by n1ngu** [comment]
@mrparkers because github is serving multiple certificate chains, a single 
```
data "tls_certificate" "github" {
  url = "https://token.actions.githubusercontent.com/.well-known/openid-configuration"
}
```
can't fetch them all. See https://github.com/aws-actions/configure-aws-credentials/issues/357#issuecomment-1610207576
