### ISSUE TITLE
GitHub OIDC is now using library of trusted CAs

### ISSUE THREAD

**Issue by wellsiau-aws** [aws-actions/configure-aws-credentials#763]
### Describe the issue

I noticed that the GitHub action identity provider in the AWS IAM console now has a banner as follow:

```
AWS secures communication with this OIDC identity provider (IdP) using our library of trusted CAs rather than using a certificate thumbprint to verify the server certificate of your IdP. 
Your legacy thumbprint(s) will remain in your configuration but will no longer be needed for validation.
```

This should permanently solve the frequent problems as reported in #357 

I suggest that to add short blurb in the [sample-iam-oidc-cloudformation-template](../#sample-iam-oidc-cloudformation-template) to account for this changes.

**Comment by peterwoodworth** [comment]
We're on it, thanks for noticing this and letting us know!
