### ISSUE TITLE
Create a profile rather than export env vars

### ISSUE THREAD

**Issue by Moulick** [aws-actions/configure-aws-credentials#800]
### Describe the feature

Add a new option to create a profile with the credentials rather than exporting the credentials as ENV Vars

### Use Case

Many times, there is a need to have multiple credentials configured for jobs. This is particularly necessary when running some IAC tools and scripts across several AWS accounts at once. The best way to use multiple short-lived credentials is via profiles as supported by the AWS SDK(s).

### Proposed Solution

Have a new flag `profile-name` that creates a profile with the name and sets the credentials. I think setting the `profile-name` should also disable setting the env vars to prevent both profile and env vars being set at the same time, leading to confusion if the action is used multiple times and incorrect credentials being used in the subsequent steps.

### Other Information

Currently I am using a custom composite action based on `aws-actions/configure-aws-credentials@v3` forked from https://github.com/mcblair/configure-aws-profile-action to achieve this.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
Thanks for the request - this should be a duplicate with #112
