### ISSUE TITLE
 Need for sts:TagSession Permission

### ISSUE THREAD

**Issue by luke-perry** [aws-actions/configure-aws-credentials#81]
We are using the [AWS Deploy CloudFormation Stack Github Action](https://github.com/marketplace/actions/aws-cloudformation-deploy-cloudformation-stack-action-for-github-actions) to configure AWS accounts that are created via AWS Organizations.

Of course, we are first using this action for credential configuration and assuming a role. However, this credential action does [session tagging](https://github.com/aws-actions/configure-aws-credentials/blob/master/index.js#L49) which requires the `sts:TagSession` permission. This need for tagging is of course [documented in the readme of this action](https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions#permissions-for-assuming-a-role). However, in our case, the tag is needed in the trust policy of the `OrganizationAccountAccessRole` in the member account that is created by AWS Organizations. 

This results in manual effort/intervention to our automated process. We have to configure the root user for the member account created by AWS Organizations to add the permission to the trust policy. 

Would it be possible to make the session tagging optional?

**Comment by KeifferCulbreth** [comment]
@allisaurus if you think the functionality that @luke-perry suggested is desired, I can make a PR

**Comment by allisaurus** [comment]
@KeifferCulbreth If you're willing to submit a PR that allows opting-out of session tagging, that would be great, thank you!
