### ISSUE TITLE
SecretAccessKey contains special characters

### ISSUE THREAD

**Issue by shaylevin89** [aws-actions/configure-aws-credentials#821]
### Describe the bug

when I try to assume a role it works usually. BUT sometimes I get error
usually works

### Expected Behavior

1. this will not happen
2. if it happens it should be more informative. like which character is not allowed. and maybe the option to choose accepted charecters

### Current Behavior

when I try to assume a role it usually works. BUT sometimes I get this error:
Error: Could not assume role with OIDC: SecretAccessKey contains special characters.
this behaviour happens 1 time every ~100 runs.

### Reproduction Steps

there is no such. its happen randomly

**Comment by peterwoodworth** [comment]
Are you using `v3`? This functionality should be disabled by default. Please provide your workflow file?

**Comment by shaylevin89** [comment]
thanks for the reply. we r using v3.0.0.
we r using this action via another composite action. this is the composite action:

runs:
  using: "composite"
  steps:
    - name: configure aws credentials for dev
      uses: aws-actions/configure-aws-credentials@v3.0.0
      with:
        role-to-assume: arn:aws:iam::*******:role/*********
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_SECRET_REGION }}
