### ISSUE TITLE
Node 18

### ISSUE THREAD

**Issue by ttung** [aws-actions/configure-aws-credentials#839]
### Describe the feature

Upgrade this action to use Node 18.

### Use Case

This tool uses Node 16.  That is EOL as of today (2023-09-11).  Can this upgrade to the next LTS version (Node 18)?

When I need to comply with requirements to use software that is not EOL'ed, I am not able to use this.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
`node18` isn't an option provided by GitHub, however `node20` is 🙂

**Comment by ttung** [comment]
The latest three LTS version [should](https://github.com/actions/runner-images#software-and-image-support) be available if you switch to https://github.com/actions/setup-node.
