### ISSUE TITLE
Link to details on Assuming a Role goes nowhere

### ISSUE THREAD

**Issue by jwscook** [aws-actions/configure-aws-credentials#877]
### Describe the issue

The reader is directed to the link [Assuming a Role](https://github.com/aws-actions/configure-aws-credentials#assuming-a-role) for more details, but this link goes nowhere are no more details are available.

Where should the reader get more details on this?

**Comment by peterwoodworth** [comment]
Thanks for the callout, the correct link should probably be https://github.com/aws-actions/configure-aws-credentials#OIDC
