### ISSUE TITLE
tokens.actions.githubusercontent.com in document does not work

### ISSUE THREAD

**Issue by fartbagxp** [aws-actions/configure-aws-credentials#906]
### Describe the issue

The link tokens.actions.githubusercontent.com in the section: https://github.com/aws-actions/configure-aws-credentials#note-about-ghes does not work.
![image](https://github.com/aws-actions/configure-aws-credentials/assets/8839850/3ef8e6b3-b232-4679-ad79-5cb0dbaee205)

`tokens` should be `token`, and that'll work.
Requesting URL to be changed to `token.actions.githubusercontent.com`

**Comment by tim-finnigan** [comment]
Thanks @fartbagxp! Created https://github.com/aws-actions/configure-aws-credentials/pull/907.
