### ISSUE TITLE
If the assumed role name is `GitHubActions` the action will fail with a non specific error

### ISSUE THREAD

**Issue by kle-sd** [aws-actions/configure-aws-credentials#953]
### Describe the issue

Ran into this for a few hours tonight where I was naming my role to be assumed `GitHubActions` and was failing to assume role via OIDC. The action spat out this error. Simply renaming the role to anything else ran successfully.

```
Could not assume role with OIDC: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

The pitfall is especially time consuming because web searching the error leads to posts suggesting to fix the conditions in the IAM trust policy which are unrelated.

I suggest either highlighting this restricted role name in the documentation, or fixing the issue preventing use of this role name.

**Comment by tim-finnigan** [comment]
Thanks for reporting this issue.

**Comment by zchenyu** [comment]
Oh nevermind, it seems the "fix" was just to document that it doesn't work. Maybe re-open the issue?

**Comment by packruler** [comment]
Using `GitHub-Actions-Runner` also breaks for invalid reasons.

**Comment by EricWiener** [comment]
Using `GitHubActionsDeploy_RepoName` also didn't work with the same not helpful message

**Comment by BernhardRode** [comment]
Also GitHubRole fails...

**Comment by BennettDixon** [comment]
`github-actions-xx` also fails - appears to fail regardless of case with anything 'Github/github' in-front, but I didn't do too much testing on it: `g-actions-xx` worked for me.
