### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by labeveryday** [aws-actions/configure-aws-credentials#997]
### Describe the bug

When running the action I get this message::

`[AssumeRoleAndCallIdentity](https://github.com/labeveryday/cloud-resume-challenge-frontend/actions/runs/7769614948/job/21188876215)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, aws-actions/configure-aws-credentials@v1.7.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

### Expected Behavior

The code should be updated before it is no longer supported and/or causes issues. 

### Current Behavior

I receive the warning every time the action is run. 

### Reproduction Steps

On push

### Possible Solution

Updating the Node.js

**Comment by Moulick** [comment]
@labeveryday v4 uses node 20, please upgrade, you can see the changelog here https://github.com/aws-actions/configure-aws-credentials/blob/main/CHANGELOG.md

**Comment by tim-finnigan** [comment]
> @labeveryday v4 uses node 20, please upgrade, you can see the changelog here https://github.com/aws-actions/configure-aws-credentials/blob/main/CHANGELOG.md

+1 to this - please let us know if you have any issues using v4.
